### ISSUE TITLE
unexpected results for the ternary operator

### ISSUE THREAD

**Issue by aalucaci** [grddavies/rtern#3]
Hello,
being familiar with the ternary operator from the C++ language, I thought I would give it a try and use the ternary operator defined in your package in R. Unfortunately I found a few cases which don't give the results I naively expected:

```r
library(rtern)

# case 1) as expected
TRUE ? c("yes", "maybe") : "no"
# "yes"   "maybe"

# case 2) as expected
TRUE ? c("yes", "maybe") : c("no", "really no")
# "yes"   "maybe"

# case 3) UNEXPECTED
out <- c(TRUE, FALSE) ? c("yes", "maybe") : c("no", "really no")
str(out)
# List of 2
# $ : chr "yes"
# $ : language c("no", "really no")

# case 4) UNEXPECTED
x <- c("yes", "maybe")
y <- c("no", "really no")
out <- c(TRUE, FALSE) ? x : y
str(out) 
# List of 2
# $ : chr "yes"
# $ : symbol y

# case 5) UNEXPECTED
rhs <- c("yes", "maybe")
lhs <- c("no", "really no")
c(TRUE, FALSE) ? rhs : lhs
# Error in rhs:lhs : NA/NaN argument
# In addition: Warning messages:
#   1: In rhs:lhs : numerical expression has 2 elements: only the first used
# 2: In rhs:lhs : numerical expression has 2 elements: only the first used
# 3: In eval(rhss[[1]]) : NAs introduced by coercion
# 4: In eval(rhss[[1]]) : NAs introduced by coercion
```
I would appreciate if you could comment on this and/or maybe tell me what I do wrong.

For completeness: I use R version 4.1.2 and rtern version 0.1.1.

Thank you for your time,
Angela

**Comment by grddavies** [comment]
Hi Angela,

Theres clealy a bug in how I am parsing and evaluating the expressions.

You bring up some interesting examples here and in your blog, cases which I hadn't considered defining behaviour for in the rtern package. I'm not so familair with C++, can its ternary operator handle conditionals in vector/matrix structures? If so I'd like to replicate its behaviour.

Could you please describe the expected behaviour for case 3? Cases 4 and 5 should result in the same.

In addition to the cases you point out here, an example from your blog results in this obscure error:
```r
> NULL == 4 ? "yes" : "no"
Error in rhss[[2 - as.numeric(lhs)]] : 
  attempt to select less than one element in get1index
```
Probably `logical(0)` should be returned in this case!

Thanks for bringing this to my attention,
Gethin

**Comment by aalucaci** [comment]
Hello Gethin,
thank you for you quick reply and for having a look at my examples.

As far as I know, C++ cannot handle conditionals in vector structures. 

As for the examples, here are my expectations:

```r
library(rtern)
# case 3)
c(TRUE, FALSE) ? c("yes", "maybe") : c("no", "really no")
```

I would naively expect this to be a vectorized operation, i.e. an output like this:
```r
  c("yes", "really no")
```

However, assuming this operation is really vectorized, one should also consider one should happen when the values in the involved expressions have different lengths. For example:
  
```r
  c(TRUE, FALSE) ? c("yes", "maybe") : "no"
```

Shall one just assume that we actually have `c("no", "no")` and give this result:
  ```r
  c("yes", "no")
```

What does one do then in somewhat more complicated cases like this one?
```r
  c(TRUE, FALSE, TRUE) ? c("yes", "maybe", "ok") : c("no", "really no")
```

My guess is that a safe way would be to ensure that the values have equal lengths but only when the result of the expression before "?" has length > 1. The use case that I have in mind when I say this:
 ```r
foo <- function() {letters[1:10]}
bar <- function() {"A"}
TRUE ? foo() : bar()
```

As for this example:
```r
NULL == 4 ? "yes" : "no"
```

To my understanding, the ternary operator is at the first glance a short form of if/else. With this in mind I could rewrite the code like this:
 ```r
if (NULL == 4) {
  "yes"
} else {
  "no"
}
```

This results in an error, since the argument of if must be a logical of length 1. Similarly I would naively also expect that 
```r
NULL == 4 ? "yes" : "no"
```

gives an error, and NOT that it returns a logical(0).

In the end, one should decide if vectorized expressions are allowed for the ternary operator, and if yes, handle the different lengths properly.

Whatever the decision, I think it's important that the behaviour is documented such that the users know what do they get one using this operator.

Kind regards,
Angela

**Comment by aalucaci** [comment]
Hello Gethin,
just wanted to report another case which a colleague just brought to my attention:
```r
library(rtern)

foo <- function(param)
{
  out <- param ? "yes" : "no"
  print(str(out))
}

foo(TRUE)
# Error in eval(lexpr[[3]]) : object 'param' not found 
```

I understand evaluation in R is a complex subject, so probably this is not easy to fix.
However, my colleague and I like the idea of this operator, and we would appreciate if this could be fixed.

Kind regards
Angela

**Comment by grddavies** [comment]
Hi Angela,

I've just pushed a dev version of the package which should fix these issues.

Feel free to install it and let me know how you get on.

```r
#install.packages("remotes")
remotes::install_github("grddavies/rtern", ref = "dev")
```

The behaviour should now match `ifelse` with vector conditions and cases. ie replicating a the condition vectors to match the case length.

I'll update the docs when I have some time to make this clearer, and release a new version.

Kind regards,
Gethin

**Comment by aalucaci** [comment]
Hello Gethin,
thank you for the update.

Things look indeed better with the dev version. 

Here are a few cases which still do not behave as I would naively expect:

```r
NULL ? "yes" : "no"
# received: Error in parse_tree[[1]] : subscript out of bounds
# expected: error because the test is not logical

c(TRUE, NULL) ? "yes" : "no"
# received: "yes"
# expected: error because the test is not logical

c(NA, FALSE) ? "yes" : "no"
# received: [1] NA   "no"
# expected: error because the test contains NA

c(TRUE, FALSE) ? "yes" : "no" 
# received: [1] "yes" "no" 
# expected: error because length of test differs from length of yes and no

c(TRUE, FALSE) ? letters[1:3] : LETTERS[1:2]
# received: [1] "a" "B"
# expected: error because length of test differs from length of yes and no
```

As already said, my expectations are naive, feel free to disregard them if not applicable.

Kind regards,
Angela

**Comment by grddavies** [comment]
Hi Angela, 

The first case is a definitely a bug which needs handling.

In the other cases `?:` is reproducing the behaviour of `ifelse`, which it uses it under the hood. I think `ifelse` is well designed for flexible matrix and vector logic. 

To make `?:` functionality significantly different from `ifelse`, and potentially create some specific use-cases for it, I am considering that it could return a list of the `if_true`, `if_false` conditions, regardless of their dimensions/type.
ie 
``` r
library(rtern)
x <- data.frame(letters = LETTERS, numbers = 1:26)
y <- matrix(1:9, 3)
out <- c(FALSE, TRUE) ? x : y
str(out)
#> List of 2
#>  $ : int [1:3, 1:3] 1 2 3 4 5 6 7 8 9
#>  $ :'data.frame':    26 obs. of  2 variables:
#>   ..$ letters: chr [1:26] "A" "B" "C" "D" ...
#>   ..$ numbers: int [1:26] 1 2 3 4 5 6 7 8 9 10 ...
```

This would be more like a vectorised `if (cond) if_true else if_false` , and would then (to me) make more sense to handle `NULL`/`NA` as `if` does.

This could be used to call code blocks for their side-effects, rather than their output, as `if-else` statements are often used, like this JS example:

```js
var authenticated = true;
var nextURL = authenticated ? (
    alert('You will redirect to admin area'),
        '/admin'
) : (
    alert('Access denied'),
        '/403'
);
// redirect to nextURL here
console.log(nextURL); // '/admin'
```

Let me know what you think.

Kind regards,
Gethin

**Comment by aalucaci** [comment]
Hello Gethin,
personally I would use the ternary operator only in the "one line" cases. 

As soon as there is more than one line, as in your JS example, I prefer to use if/else, which I find more readable for complex cases. But then again, this is of course personal taste. 

Whatever you decide for, as long as the obvious bugs are fixed and the behavior is documented, everything is OK.

Kind regards,
Angela
